kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume	
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/minio"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: minio
          image: bitnami/minio:latest
          env:
          - name: MINIO_ACCESS_KEY
            value: akey
          - name: MINIO_SECRET_KEY
            value: skey
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data/ob
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio

spec:
  ports:
    - port: 9000
      targetPort: 9000
  externalIPs:
  selector:
    app: minio

