apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: orson88/recsys:backend
    ports:
    - containerPort: 8080
    command:
        - /bin/sh
        - -c
        - |
          cd /var/ 
          wget https://raw.githubusercontent.com/orson88/hse_mlds_recsys_project/main/datasets/popular_songs.csv
          wget https://github.com/orson88/hse_mlds_recsys_project/raw/main/app/data/train_user_item_matrix.npz
          wget https://github.com/orson88/hse_mlds_recsys_project/raw/main/app/models/als_best_params.pkl
          cd /app/
          uvicorn app:app --host=0.0.0.0 --port=8080